// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: Login.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Protobuf {

  /// <summary>Holder for reflection information generated from Login.proto</summary>
  public static partial class LoginReflection {

    #region Descriptor
    /// <summary>File descriptor for Login.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static LoginReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "CgtMb2dpbi5wcm90bxIIcHJvdG9idWYiVgoFTG9naW4SCwoDYWFhGAEgASgB",
            "EiEKA2JiYhgCIAEoDjIULnByb3RvYnVmLkxvZ2luLlR5cGUiHQoEVHlwZRIH",
            "CgNuaWwQABIFCgFhEAESBQoBYhACYgZwcm90bzM="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Protobuf.Login), global::Protobuf.Login.Parser, new[]{ "Aaa", "Bbb" }, null, new[]{ typeof(global::Protobuf.Login.Types.Type) }, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  public sealed partial class Login : pb::IMessage<Login> {
    private static readonly pb::MessageParser<Login> _parser = new pb::MessageParser<Login>(() => new Login());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<Login> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Protobuf.LoginReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Login() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Login(Login other) : this() {
      aaa_ = other.aaa_;
      bbb_ = other.bbb_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Login Clone() {
      return new Login(this);
    }

    /// <summary>Field number for the "aaa" field.</summary>
    public const int AaaFieldNumber = 1;
    private double aaa_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public double Aaa {
      get { return aaa_; }
      set {
        aaa_ = value;
      }
    }

    /// <summary>Field number for the "bbb" field.</summary>
    public const int BbbFieldNumber = 2;
    private global::Protobuf.Login.Types.Type bbb_ = global::Protobuf.Login.Types.Type.Nil;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Protobuf.Login.Types.Type Bbb {
      get { return bbb_; }
      set {
        bbb_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as Login);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(Login other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.Equals(Aaa, other.Aaa)) return false;
      if (Bbb != other.Bbb) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (Aaa != 0D) hash ^= pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.GetHashCode(Aaa);
      if (Bbb != global::Protobuf.Login.Types.Type.Nil) hash ^= Bbb.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (Aaa != 0D) {
        output.WriteRawTag(9);
        output.WriteDouble(Aaa);
      }
      if (Bbb != global::Protobuf.Login.Types.Type.Nil) {
        output.WriteRawTag(16);
        output.WriteEnum((int) Bbb);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (Aaa != 0D) {
        size += 1 + 8;
      }
      if (Bbb != global::Protobuf.Login.Types.Type.Nil) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) Bbb);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(Login other) {
      if (other == null) {
        return;
      }
      if (other.Aaa != 0D) {
        Aaa = other.Aaa;
      }
      if (other.Bbb != global::Protobuf.Login.Types.Type.Nil) {
        Bbb = other.Bbb;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 9: {
            Aaa = input.ReadDouble();
            break;
          }
          case 16: {
            Bbb = (global::Protobuf.Login.Types.Type) input.ReadEnum();
            break;
          }
        }
      }
    }

    #region Nested types
    /// <summary>Container for nested types declared in the Login message type.</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static partial class Types {
      public enum Type {
        [pbr::OriginalName("nil")] Nil = 0,
        [pbr::OriginalName("a")] A = 1,
        [pbr::OriginalName("b")] B = 2,
      }

    }
    #endregion

  }

  #endregion

}

#endregion Designer generated code
